---
last_mapped: REPLACE_TIMESTAMP
total_files: REPLACE_COUNT
analysis_method: CodeIndex static analysis + Oracle documentation
confidence: REPLACE_LEVEL
generated_docs:
  - CODEBASE_MAP.md
codeindex_static_analysis: REPLACE_YES_OR_NO
---

# Codebase Map

> Auto-generated by Codebase Oracle. Last mapped: REPLACE_TIMESTAMP
> Analysis method: CodeIndex static analysis + Oracle documentation

<!-- ORACLE:OVERVIEW
Lead fills this section.

Data sources:
1. Parse codebase_map.json for project-level metrics, communities, hubs
2. Use overview.md.tpl template structure for project overview
3. Summarize in 2-3 sentences: what the system is, what it does, who it's for
-->

## System Overview

REPLACE: 2-3 sentence summary

**Stack**: REPLACE: key technologies
**Architecture**: REPLACE: pattern name

## Source Documentation

<!-- ORACLE:SOURCES
List the documentation sources used.

CodeIndex static analysis outputs:
- codebase_map.json: components, edges, metrics, communities, hubs
- dependency_graphs/*.json: per-module dependency data
- templates/*.tpl: doc structure templates
- graph.html: AI-generated interactive viewer (from skill's graph.html.tpl, not CodeIndex)

```bash
# Check CodeIndex static analysis
ls docs/codebase_map.json docs/dependency_graphs/ docs/templates/ 2>/dev/null

# List Oracle-written module docs
ls docs/*.md | grep -v CODEBASE_MAP | grep -v c4 | grep -v key-flows | grep -v dependency
```
-->

**CodeIndex Static Analysis**: REPLACE_YES_OR_NO

| Source | Description |
|--------|-------------|
| [codebase_map.json](codebase_map.json) | Components, edges, metrics, communities, hubs |
| dependency_graphs/ | Per-module dependency JSON data |
| templates/ | CodeIndex doc structure templates |
| [graph.html](graph.html) | AI-generated interactive dependency viewer |
| REPLACE | REPLACE: list Oracle-written module .md files |

## Static Analysis Metrics

<!-- ORACLE:METRICS
From CodeIndex codebase_map.json:
```bash
cat docs/codebase_map.json | python3 -c "
import json, sys
data = json.load(sys.stdin)
nodes = data.get('nodes', [])
edges = data.get('edges', [])
communities = data.get('communities', [])
print(f'Components: {len(nodes)}')
print(f'Edges: {len(edges)}')
print(f'Communities: {len(communities)}')
"
```
-->

| Metric | Count |
|--------|-------|
| Components | REPLACE |
| Edges | REPLACE |
| Communities/Modules | REPLACE |
| Files Analyzed | REPLACE |

## Architecture Docs

<!-- ORACLE:DOC_INDEX
Only include rows for docs that were actually generated.
-->

### Oracle-Written Analysis

| Document | Description |
|----------|-------------|
| [Architecture](architecture.md) | System context, C4 diagrams, design decisions |
| [Dependencies](dependencies.md) | Dependency graph, hub analysis, blast radius |
| [Key Flows](key-flows.md) | Cross-module execution paths |
| [API Surface](api-surface.md) | Public interfaces and endpoints |
| [Data Model](data-model.md) | Data structures and schemas |
| [Infrastructure](infrastructure.md) | Deployment and infrastructure |
| [Product Requirements](product-requirements.md) | Inferred product requirements |

### Oracle-Written Module Docs

<!-- ORACLE:MODULE_DOCS
List Oracle-written module docs:
```bash
ls docs/*.md | grep -v CODEBASE_MAP | grep -v c4 | grep -v key-flows | grep -v dependency
```
-->

| Document | Description |
|----------|-------------|
| REPLACE | REPLACE: module .md files |

## Hub Files

<!-- ORACLE:HUBS
From CodeIndex codebase_map.json:
```bash
cat docs/codebase_map.json | python3 -c "
import json, sys
data = json.load(sys.stdin)
nodes = data.get('nodes', [])
# Find high fan-in nodes (hubs)
hubs = sorted(
    [n for n in nodes if n.get('fan_in', 0) >= 3],
    key=lambda n: n.get('fan_in', 0),
    reverse=True
)[:10]
for h in hubs:
    print(f'{h[\"name\"]}: fan_in={h.get(\"fan_in\",0)}, fan_out={h.get(\"fan_out\",0)}')
"
```
-->

| Package | Dependents | Stability | Risk |
|---------|-----------|-----------|------|
| REPLACE | REPLACE | REPLACE | REPLACE |

## Module Guide

<!-- ORACLE:MODULES
From codebase_map.json communities and Oracle-written module docs.

```bash
cat docs/codebase_map.json | python3 -c "
import json, sys
data = json.load(sys.stdin)
for comm in data.get('communities', []):
    print(f'{comm[\"name\"]}: {comm.get(\"node_count\", 0)} components')
"
```
-->

### REPLACE: Module Name

**Purpose**: REPLACE
**Layer**: REPLACE
**Detailed docs**: [{module}.md]({module}.md)

| Directory | Purpose | Layer |
|-----------|---------|-------|
| REPLACE | REPLACE | REPLACE |

## Confidence Assessment

Overall: REPLACE_BAR REPLACE_PERCENTAGE%

**High confidence:**
- REPLACE — REPLACE_REASON

**Lower confidence:**
- REPLACE — REPLACE_REASON

## △ Caveats

<!-- ORACLE:CAVEATS
If confidence < 5, list assumptions and gaps.
-->

REPLACE: assumptions and gaps (delete if confidence = 5)
